#!/bin/bash -e

pushd ${BASH_SOURCE%/*} > /dev/null

# Linking testcheck
npm link > /dev/null

# Loop through integrations, testing each
for integration in *; do
  [ -d "${integration}" ] || continue
  printf "\e[43;30m Test Integration: ${integration} \e[0m\n\n"
  pushd ${integration} > /dev/null
  npm link testcheck > /dev/null
  yarn
  npm test
  popd > /dev/null
done

popd > /dev/null
